import Head from 'next/head'
import Avatar from '../components/Avatar'
import styles from '../styles/Home.module.css'
// import profilePic from '../public/images/my_faceshot.JPG'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* Header */}
      <header className="flex w-full p-5 justify-between text-sm text-gray-700">
        {/* Left */}
        <div className='flex space-x-4 items-center'>
          <p className='link'>About</p>
          <p className='link'>Store</p>
        </div>

        {/* Right */}
          <div className='flex space-x-4 items-center'>
            <p className='link'>Gmail</p>
            <p className='link'>Images</p>

            {/* Icon */}


            {/* Avatar */}
            <Avatar />
          </div>
      </header>

      {/* Body */}
 
      {/* Footer */}
    </div>
  )
}
